# -*- coding: utf-8 -*-
"""rim_center_modified.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iwr_m3N2Lbls2G11ySdpsxXaC8lk-w56
"""

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

# создаем матрицу смежности графа
adj_matrix = np.array([
    [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0]
])

# создаем граф из массива NumPy
G = nx.from_numpy_array(adj_matrix)

# находим радиус графа
radius = nx.radius(G)

# размещаем стражей в центре графа
center = nx.center(G)

# окрашиваем вершины
colors = []
for node in G.nodes():
    if node in guards:
        colors.append('red')
        G.nodes[node]['label'] = str(len(guards))
    else:
        if nx.shortest_path_length(G, center[0], node) <= radius:
            colors.append('green')
        else:
            colors.append('blue')

# рисуем граф
pos = nx.spring_layout(G)
nx.draw(G, pos, node_color=colors, with_labels=True)
plt.show()
# выводим количество стражей
print("Количество стражей:", len(guards))